sjdemartini/mui-tiptap

src/MuiTiptapContent.tsx, src/MuiTiptapOutlinedField.tsx, src/demo/Editor.tsx
We shouldn't add default padding whenever the editor is in edit mode, generally.
=> Move default content padding to within OutlinedField only

src/extensions/LinkBubbleMenuHandler.ts
Based on docs here https://tiptap.dev/api/commands#dry-run-for-commands
=> Handle `can()` dry-runs for LinkBubbleMenuHandler commands

example/package.json, example/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/EditLinkMenuContent.tsx
The form behavior should essentially be identical, but we can reduce the bundle impact and simplify things by reducing external dependencies.
=> Use vanilla React for link-editing form, and remove react-hook-form dependency

src/ViewLinkMenuContent.tsx, src/extensions/ResizableImageComponent.tsx, src/hooks/useDebouncedFocus.ts, src/styles.ts, src/utils/debounceRender.tsx
Along the lines of MUI's suggestion here https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports about how library developers should use default imports.
Still to do later: use default imports for MUI components, MUI icons, and react-icons.
=> Replace lodash named imports with default imports

src/MenuBar.tsx, src/TableBubbleMenu.tsx
We primarily care about debouncing for performance when performing many consecutive actions, but it's fine to let the first update render, which should generally make the menus feel quite a bit snappier.
=> Improve snappiness of MenuBar & TableBubbleMenu with leading debounce render

src/TableBubbleMenu.tsx, src/hooks/useDebouncedFocus.ts
Without these changes, since introducing `leading: true` to the outer `debouncedRender`, clicking a button would prematurely close the bubble menu. Now instead, we use a debounced focused state to determine whether the menu is open, and just debounce the rendering of the TableMenuBar itself (not the whole bubble menu).
=> Fix table bubble menu debouncing and focus

src/RichTextContent.tsx, src/styles.ts
This way, the styles are applied anywhere `getEditorStyles` is used "automatically", without needing style overrides via `RichTextContent`'s conditional classes.
=> Generalize the styles used for read-only tables

.github/workflows/build-test.yml
GitHub Actions allows 20 concurrent jobs as is
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits, which is probably more than we'll ever use. This avoids the overall build being marked as "failing" (in the README CI badge) when pushing a tag that runs a "redundant" version of the build-test job, and reduces noise from "build failed" emails.
=> Don't cancel in-progress jobs for same branch

src/index.ts
In case users want to access the editor this way themselves within nested components.
=> Export context utilities

src/ControlledBubbleMenu.tsx, src/TableBubbleMenu.tsx
Don't have the bubble menu move around as much as the table is being edited (columns and rows being added, removed, or resized), by fixing it to the `top-start` placement. And through a workaround with PopperJS flip padding, we also now try to ensure that we do not cover up a (potentially sticky) menu bar above the editor, and only fall back to bottom positions if the top has no room.
=> Improve table bubble menu placement by affixing to top start

package.json, pnpm-lock.yaml
As of https://github.com/sjdemartini/mui-tiptap/pull/22, no longer used.
=> Remove now-unneeded hoist statics package

src/styles.ts
The border color wasn't taking effect due to `border: 3px solid` coming *after* it, and so overriding the color (back to its default of "initial"). To avoid the ordering problems altogether, this changes the border CSS to be set via its individual parts rather than using the `border` shorthand partly, and `border-color` separately.
=> Fix collaboration cursor "dot" color

src/context.ts
This is preferable to quietly returning `null` and just rendering no editor state/content, to help users quickly see and fix problems.
=> Add error messaging if editor not provided

example/src/PageContentWithEditor.tsx, src/ControlledBubbleMenu.tsx, src/LinkBubbleMenu/index.tsx, src/MenuBar.tsx, src/RichTextContent.tsx, src/RichTextEditor.tsx, src/TableBubbleMenu.tsx, src/demo/Editor.tsx
This allows a lot more flexibility, and doesn't assume that users want to use these bubble menus, or if they do, that they want to use them with their default props. (e.g., someone may want to use a custom version of one of these bubble menus)
=> Allow for style and prop overrides in bubble menus, and remove from RichTextContext

src/LinkBubbleMenu/index.tsx, src/TableBubbleMenu.tsx
These menus are exclusively used for editing, so make sure they don't show up in read-only mode.
=> Don't show Link and Table bubble menus when editor isn't editable

src/ControlledBubbleMenu.tsx, src/TableBubbleMenu.tsx
Typically, bubble menus are interacted with alongside the content, so with an `elevation={10}` in light mode in MUI, it would tend to cast a relatively large shadow, which could be annoying (e.g. with the table menu) if you're trying to edit the content that's directly next to the menu. This adjusts it down slightly while still maintaining enough elevation to be visually distinct from the editor content.
Now users can also tweak this and other fields when they use the `TableBubbleMenu`/`LinkBubbleMenu`/`ControlledBubbleMenu`.
=> Reduce bubble menu default elevation, and allow for customization of Paper props

package.json
By removing this, the package will default to being a CJS package. Other packages (e.g., tss-react, mui-datatables, MUI, react-pdf) do not specify this either.
From testing installing in a third-party application, this fixes an issue in testing code that imports `mui-tiptap` (at least when using vitest):
```
Error: Cannot find module '/path/node_modules/mui-tiptap/dist/esm/ControlledBubbleMenu' imported from /path/node_modules/mui-tiptap/dist/esm/index.js
```
=> Remove seemingly incorrect/unneeded `"type": "module"` field

.eslintrc.json, package.json, pnpm-lock.yaml
No devDependencies should be imported in the main project without also appearing in peerDependencies. Otherwise we risk the package breaking when installed for others.
And because we publish our types with our package, even Type imports should need to be included in dependencies or peerDependencies. So `type-fest` should really be listed as a direct dependency (as it is for other major users of type-fest, like yup, snakecase-keys, etc., and as described here
https://github.com/sindresorhus/type-fest/issues/136#issuecomment-714211609).
=> Lint against more extraneous dependencies being imported

README.md
We don't yet support the `@tiptap/pm` approach, but should once we bump our peer dependencies. For now, just mention what the peers are.
=> Don't list peer dep install steps since not accurate currently

src/LinkBubbleMenu/ViewLinkMenuContent.tsx, src/extensions/LinkBubbleMenuHandler.ts
This avoids a focus-jump when clicking away from the "Edit" form, by ensuring the bubble menu state is kept in sync. An extra precautionary fallback to `?? ""` is added for the `currentHref` just in case the menu renders when unexpected and no `href` is available, since this can cause a crash (though that scenario is likely resolved by our more deliberate menu-closing, and handled here just as a defensive precaution).
=> Fix link bubble menu state when clicking out or changing selection

src/RichTextEditor.tsx
https://github.com/ueberdosis/tiptap/issues/3764#issuecomment-1546854730
Otherwise updating `content` of `RichTextEditor` will give the following error (as of the recent Tiptap version bump):
```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
at RichTextEditor (http://localhost:5173/src/RichTextEditor.tsx?t=1686945132689:21:90)
```
=> Avoid flushSync errors in useEffect

src/styles.ts
There was a mistake in the original approach, since setting `"display: none"` on `&.resize-cursor` would actually be hiding the entire ProseMirror document, as opposed to some cursor element. This didn't appear very obviously in Chrome (though there were times where you could get it to flash slightly when hovering over a column divider), but in Firefox it was much more drastic, where the content would disappear/reappear, causing the page scroll position to rapidly/unexpectedly change any time a user's cursor crossed over a column border.
Also, it was still possible to drag and resize a column, despite it being in read-only mode and not showing a resize cursor, since the editor and the table were still responding to pointer events (and the underlying prosemirror-tables `columnResizing` …
=> Fix bug interacting with and hovering over table columns in read-only mode

src/LinkBubbleMenu/ViewLinkMenuContent.tsx
It seems `$from` doesn't typically properly allow us to grab the link range anymore (presumably after a Tiptap version bump), though `$to` does. This switches to `$to` so that the "view link" bubble menu shows the text content and not just the link itself.
=> Make "View Link" bubble menu properly show text

src/controls/MenuButtonAddImage.tsx, src/controls/MenuButtonAddTable.tsx, src/controls/MenuButtonBlockquote.tsx, src/controls/MenuButtonBold.tsx, src/controls/MenuButtonBulletedList.tsx, src/controls/MenuButtonCode.tsx, src/controls/MenuButtonCodeBlock.tsx, src/controls/MenuButtonEditLink.tsx, src/controls/MenuButtonIndent.tsx, src/controls/MenuButtonItalic.tsx, src/controls/MenuButtonOrderedList.tsx, src/controls/MenuButtonRemoveFormatting.tsx, src/controls/MenuButtonStrikethrough.tsx, src/controls/MenuButtonSubscript.tsx, src/controls/MenuButtonSuperscript.tsx, src/controls/MenuButtonTaskList.tsx, src/controls/MenuButtonUnindent.tsx, src/controls/index.ts, src/demo/EditorMenuControls.tsx
As mentioned in https://github.com/sjdemartini/mui-tiptap/issues/52#issuecomment-1595936811
This also now includes the `MenuButtonAddImage` in the demo in local dev, with a `window.prompt` to get a URL from the user:
=> Allow users to override all props for all menu buttons, and include image button in demo

.github/workflows/build-test.yml
Several underlying packages rely on `semver`, and it's failing `pnpm audit` currently:
https://github.com/sjdemartini/mui-tiptap/actions/runs/5351723011/jobs/9705882749
Per this advisory: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
But that's of very low concern for us, so just going to change CI to only report on `high` severity.
=> Change CI audit-level check to "high"

example/pnpm-lock.yaml, src/ControlledBubbleMenu.tsx
Users can now provide their own `container` or use `disablePortal` with the `ControlledBubbleMenu` (and by extension the `LinkBubbleMenu` and `TableBubbleMenu`). If not provided, it will fall back to MUI's default now (which is typically `document.body`). We used to use a hacky approach of getting an ancestor element of the editor, but that had some flaws (see commit messages for details), and this allows for more customization and the right behavior outside of modals.
With modals, like when placing the editor inside a MUI `<Dialog />`, it will be best to use an approach like the following to ensure the bubble menus appear properly "on top" of the modal:
```tsx
<Dialog open={open} ref={dialogRef}>
<RichTextEditor ...>
{() => (
<>
<LinkBubbleMenu container={dialogRef.current} /> …
```
=> Change ControlledBubbleMenu container behavior, and allow overrides

src/ControlledBubbleMenu.tsx, src/LinkBubbleMenu/index.tsx, src/controls/MenuButton.tsx, src/controls/MenuButtonEditLink.tsx, src/extensions/LinkBubbleMenuHandler.ts
Resolves https://github.com/sjdemartini/mui-tiptap/issues/53 (see comment here https://github.com/sjdemartini/mui-tiptap/issues/53#issuecomment-1595937019)
Now, the `openLinkBubbleMenu` editor command takes an optional `anchorEl` option. If the `anchorEl` is provided, it's used to override the anchor point for positioning the bubble menu. Each call to `openLinkBubbleMenu` will reset the anchor based on the provided argument. If not provided, the bubble menu will be anchored to the location in the editor content where the link appears or will appear (as was previously always the case, with out the ability to override).
Now the `MenuButtonEditLink` uses the `anchorEl` option to anchor the menu button to the `MenuButtonEditLink`, so that when clicking to open the menu, it appears right next …
=> Anchor link bubble menu to link button when opening via button

package.json, pnpm-lock.yaml, src/controls/MenuButtonAlignCenter.tsx, src/controls/MenuButtonAlignJustify.tsx, src/controls/MenuButtonAlignLeft.tsx, src/controls/MenuButtonAlignRight.tsx, src/controls/index.ts, src/demo/EditorMenuControls.tsx, src/demo/useExtensions.ts, src/extensions/HeadingWithAnchorComponent.tsx
As requested in https://github.com/sjdemartini/mui-tiptap/issues/52
I am separately working on a `Select` dropdown version of the TextAlign menu options (rather than individual buttons for each one), which can help conserve menu bar space, like what Google Docs does. I will roll that out later.
=> Add TextAlign menu buttons, and make HeadingWithAnchor support TextAlign

src/controls/MenuButtonTooltip.tsx, src/controls/MenuHeadingSelect.tsx, src/controls/MenuSelect.tsx, src/controls/MenuSelectTextAlign.tsx, src/controls/index.ts, src/demo/EditorMenuControls.tsx
Follow-on to https://github.com/sjdemartini/mui-tiptap/pull/69, `MenuSelectTextAlign` is an alternative to the individual `MenuButtonAlign*` components, which is more horizontally compact (similar to what Google Docs uses for text alignment selection):
That select component as well as `MenuHeadingSelect` (to be renamed later for consistency) now use improved/DRY styles, so they take up less visual space, and so that the unfocused/unhovered state looks more consistent with the menu buttons (no border shown).
=> Add new `MenuSelectTextAlign` component for TextAlign, using new `MenuSelect` component for improved styles

README.md, example/pnpm-lock.yaml, example/src/PageContentWithEditor.tsx, src/controls/MenuSelectHeading.tsx, src/controls/index.ts, src/demo/EditorMenuControls.tsx
For consistency with `MenuSelectTextAlign`, and all of the `MenuButton*` components.
=> [breaking change] Rename `MenuHeadingSelect` -> `MenuSelectHeading`

src/controls/MenuSelectHeading.tsx
Now that the caret icon and padding are narrower (thanks to `MenuSelect`), the overall width can be narrower.
=> Reduce fixed width of SelectHeading component

src/controls/MenuSelectHeading.tsx
Whoops, though https://github.com/sjdemartini/mui-tiptap/pull/72 would be nice, it doesn't work properly as the "to" in "Change to..." gets truncated (shown when selecting a node that is not text).
This is still 1px narrower than before #72, but can't go any narrower than that it seems, unfortunately.
=> Increase width of MenuSelectHeading again to accommodate "Change to..."

src/extensions/HeadingWithAnchorComponent.tsx, src/extensions/ResizableImageComponent.tsx, src/extensions/ResizableImageResizer.tsx, src/hooks/index.ts, src/hooks/useDebouncedFunction.ts, src/hooks/useEditorOnEditableUpdate.ts, src/hooks/useForceUpdate.ts
For the reasons described here https://github.com/ueberdosis/tiptap/issues/3775, when toggling editable state, the `HeadingWithAnchorComponent`'s anchor wasn't showing/hiding properly. Similarly, the resizer handle in `ResizableImageComponent` would still show up when switching to editable=false, which would momentarily allow resizing when the node shouldn't have been editable.
Originally (see the first commit in this PR), I attempted to do this via listener to `editor.on("update",...)`, but ultimately decided instead to use CSS to show/how the relevant UI. That should be more performant (and is simpler) than listening to each editor update event via JS and force re-rendering with React. I've left the utilities around from that original approach (`useEditorOnEditableUpdate`, …
=> Handle editor `isEditable` state changes in extension node views

src/FieldContainer.tsx, src/RichTextField.tsx, src/hooks/useDebouncedFocus.ts, src/styles.ts
This consolidates the "outlined" vs "standard" DOM nodes/classes/styles into a single `FieldContainer` component, rather than conditionally rendering `<OutlinedField />` or some other DOM node.  With conditional-rendering approach, the `{content}` was being unmounted whenever the variant changed, which could cause a visual glitch as all Tiptap React node-views would have to re-render (so for instance, images and heading nodes would be temporarily empty during the transition).
**Breaking change**: the internal component `OutlinedField` has been renamed to `FieldContainer`. The associated utility classes like `MuiTiptap-OutlinedField-root`, `MuiTiptap-OutlinedField-notchedOutline`, etc are now named as `MuiTiptap-FieldContainer-root`, `MuiTiptap-FieldContainer-notchedOutline`, etc.
=> Don't unmount `RichTextContent` when `variant` changes

.eslintrc.json
As of 0.4.0, this option allows for exporting `const`s alongside components, since Vite supports HMR in that use-case: https://github.com/ArnaudBarre/eslint-plugin-react-refresh/tree/e92bee7ae32843d108e26b35241280b04271f8a2#allowconstantexport-v040
=> Add allowContantExport option to eslint-plugin-react-refresh

README.md, src/RichTextEditor.tsx, src/RichTextReadOnly.tsx
See discussion here https://github.com/sjdemartini/mui-tiptap/issues/91#issuecomment-1632863251
These components won't work without some extensions provided, so improve upon the typing we get from Tiptap and specify `extensions` as a required prop. Note that an empty array could still "pass" typing, but at least it's a hint that a real value is required, so shouldn't be as likely to run into a confusing error, like in https://github.com/sjdemartini/mui-tiptap/issues/91#issuecomment-1632623476. (For instance, you always need the [`Document`](https://tiptap.dev/api/nodes/document) extension at the very least.)
=> Make `extensions` required in props for RichTextEditor and ReadOnly

src/controls/MenuSelect.tsx, src/controls/MenuSelectHeading.tsx, src/controls/MenuSelectTextAlign.tsx, src/controls/index.ts
By mistake, `MenuSelect` was ignoring the `tooltipTitle` prop's value and always using "Align" as the tooltip.
This also updates `MenuSelectHeading` to allow users to specify a `tooltipTitle` (by default none is shown).
=> Fix MenuSelect tooltipTitle to use prop, and allow user to specify tooltip for MenuSelectHeading

src/controls/MenuSelect.tsx, src/controls/MenuSelectFontSize.tsx, src/controls/MenuSelectHeading.tsx, src/controls/index.ts
There are three new `MenuSelectFontSize` props to control (1) `unsetOptionContent` what text we display for the "unset" option, and (2) `hideUnsetOption` whether to hide that dropdown option entirely, and (3) `emptyValue` what to render for the Select itself when no font-size is set for the current text (to override showing the FormatSize icon).
Also, we now allow essentially all `MenuSelect` (and thus `Select`) props to be provided for both `MenuSelectFontSize` and `MenuSelectHeading`. This includes `tooltipTitle`, `sx`, `className`, etc to do styling.
For instance:
```tsx
<MenuSelectFontSize
emptyValue="16"  // Display "16" if unset since that's effectively our default font size
unsetOptionContent={<span>Reset</span>}
tooltipTitle="Change font size"
sx={{ "& .MuiSelect-select": { width: …
```
=> Make the MenuSelectFontSize and MenuSelectHeading components more configurable

.markdown-link-check-config.json, package.json
Tiptap's site is timing out a lot of the time, leading to spurious build failures like
https://github.com/sjdemartini/mui-tiptap/actions/runs/5558982096/jobs/10154638405#step:11:80
It's also slowing down the CI runs. So better to just ignore them.
The main reason we have markdown-link-check is for local markdown links (not external web pages), so this was only a nice to have.
=> Ignore Tiptap links in markdown-link-check in README

README.md, package.json, src/extensions/FontSize.ts
We only need to reference the types from that extension locally (not exported, and not used directly), so we can remove a peer dependency on it and a direct import in our `FontSize` extension. Users of the `FontSize` extension were already required to separately install the `TextStyle` extension and include it in their `extensions` array, so they will not encounter problems importing and using `FontSize` when it's not listed as a peer dep.
=> Remove @tiptap/extension-text-style as peer dep

README.md, src/RichTextEditor.tsx, src/RichTextReadOnly.tsx, src/demo/Editor.tsx
- `RichTextEditor` now will *not* reset the editor's document content when its `content` prop changes. This should make the component more generally flexible, with the option for users to customize when/how they want to `setContent`.  See the new README section on "Re-rendering RichTextEditor when content changes" for more details and alternative approaches. (This is all related to the discussion here https://github.com/sjdemartini/mui-tiptap/issues/91#issuecomment-1629911609.)
- `RichTextReadOnly` now *will* reset the editor's document content when its `content` prop changes. This is how it should've worked all along, since it's read-only and should be treated as a more "pure" renderer.
- README has been updated with more details about when/how to use these two components.
- There are …
=> Don't reset `RichTextEditor` document upon `content` prop changes, but do so with `RichTextReadOnly`

src/demo/Editor.tsx, src/demo/EditorMenuControls.tsx
This is more equivalent to how an external package will import (except `from "mui-tiptap"` rather than a relative path).
Makes it simpler to translate the local demo to the CodeSandbox linked from the README: https://codesandbox.io/p/sandbox/mui-tiptap-demo-3zl2l6
=> Change imports in demo to use top-level index

src/controls/MenuSelectTextAlign.tsx, src/controls/index.ts
This should enable users to provide their own (localized) content for each option, etc. 
Toward improving https://github.com/sjdemartini/mui-tiptap/issues/59
Example:
```tsx
<MenuSelectTextAlign
tooltipTitle="Change text alignment"
alignmentOptions={[
{
alignment: "left",
label: "Text-align left",
shortcutKeys: ["mod", "Shift", "L"],
IconComponent: FaAlignLeft,
},
{
alignment: "right",
label: "Text-align right",
shortcutKeys: ["mod", "Shift", "R"],
IconComponent: FaAlignRight,
},
]}
/>
```
=> Allow users to override MenuSelectTextAlign props, options, etc.

src/LinkBubbleMenu/EditLinkMenuContent.tsx, src/LinkBubbleMenu/ViewLinkMenuContent.tsx, src/LinkBubbleMenu/index.tsx, src/TableBubbleMenu.tsx, src/controls/TableMenuControls.tsx
Toward addressing https://github.com/sjdemartini/mui-tiptap/issues/59
```tsx
<LinkBubbleMenu
labels={{
viewLinkEditButtonLabel: "Edit link",
viewLinkRemoveButtonLabel: "Remove link",
editLinkAddTitle: "Add a new link",
editLinkEditTitle: "Update this link",
editLinkCancelButtonLabel: "Cancel changes",
editLinkTextInputLabel: "Text content",
editLinkHrefInputLabel: "URL",
editLinkSaveButtonLabel: "Save changes",
}}
/>
<TableBubbleMenu
labels={{
insertColumnBefore: "Add a new column before this",
insertColumnAfter: "Add a new column after this",
deleteColumn: "Remove current column",
}}
/>
```
=> Allow user to override LinkBubbleMenu and TableMenuControls labels to support localization

src/controls/MenuSelectHeading.tsx
Toward resolving #59 
Example:
```tsx
<MenuSelectHeading
aria-label="Heading types"
tooltipTitle="Choose heading type"
labels={{
emptyValue: "Text...",
paragraph: "Normal text",
heading1: "H1",
heading2: "H2",
heading3: "H3",
heading4: "H4",
heading5: "H5",
heading6: "H6",
}}
/>
```
=> Allow overriding labels in MenuSelectHeading to support localization

README.md, src/controls/MenuSelectFontSize.tsx, src/controls/MenuSelectHeading.tsx, src/controls/MenuSelectTextAlign.tsx
- Use `options` as the prop name for Select dropdown menu-item options everywhere
- Use `value` and `label` as the main keys in the each `options` object (e.g. instead of `alignment` and `label` in `MenuSelectTextAlign`'s `alignmentOptions` prop, it's now `value` and `label` in its `options` prop)
- In addition to supporting `options` as an array of string font-size values, add support for customized labels for the `options` in `MenuSelectFontSize`, like:
```tsx
<MenuSelectFontSize
options={[
{ value: "14px" }, // Will show "14" (trimming "px" by default if no label)
{ value: "18px", label: "Eighteen" },  // Will show "Eighteen"
{ value: "24px", label: "24px" }, // Will show "24px"
]}
/>
```
- Rename `unsetOptionContent` -> `unsetOptionLabel`
- Rename `emptyValue` -> `emptyLabel`
Old prop …
=> Make prop naming consistent between MenuSelect* components

src/demo/Editor.tsx
Since this prop/option may not be obvious to folks otherwise.
=> Add "variant" to demo editor to explain override possibilities

README.md, example/package.json, example/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/controls/MenuButtonAddTable.tsx, src/controls/MenuButtonCodeBlock.tsx, src/controls/TableMenuControls.tsx, src/icons/CodeBlock.tsx, src/icons/DeleteColumn.tsx, src/icons/DeleteRow.tsx, src/icons/InsertColumnLeft.tsx, src/icons/InsertColumnRight.tsx, src/icons/InsertRowBottom.tsx, src/icons/InsertRowTop.tsx, src/icons/LayoutColumnFill.tsx, src/icons/LayoutRowFill.tsx, src/icons/MergeCellsHorizontal.tsx, src/icons/SplitCellsHorizontal.tsx, src/icons/Table.tsx, src/icons/index.ts
Resolves https://github.com/sjdemartini/mui-tiptap/issues/119. These icons fill some gaps in the `@mui/icons-material` icon set. We now include them directly rather than importing from `react-icons` or another external package to reduce both install size and external dependencies.
We now export these internally created icons in the `"mui-tiptap/icons"` namespace, so they can be used externally if desired, like `import { InsertColumnLeft } from "mui-tiptap/icons";`
UI is unchanged:
- Remix icons: 
- Box icons:
=> Remove react-icons dependency in favor of internal versions of Remix and Box icons

src/controls/MenuSelectFontFamily.tsx, src/demo/EditorMenuControls.tsx
Rather than showing each option in the default font, we'll show each option in that option's font-family style.
Also, this changes the default emptyLabel and tooltipTitle to "Font", as that's the more familiar name that Outlook, Google Docs, etc. use.
Example:
=> Show each font family option with that font-family CSS style, and change empty/tooltip label to "Font"

src/controls/MenuSelectFontFamily.tsx, src/controls/MenuSelectFontSize.tsx, src/controls/MenuSelectHeading.tsx, src/controls/MenuSelectTextAlign.tsx, src/extensions/HeadingWithAnchorComponent.tsx, src/utils/getAttributesForEachSelected.ts, src/utils/getAttributesForMarks.ts, src/utils/getAttributesForNodes.ts, src/utils/index.ts
Summary of changes:
- `MenuSelectHeading`: when multiple different headings are selected (and no other content), show `labels.empty` (which defaults to "Change to...") rather than showing the _first_ selected heading. This will ensure you're able to update both headings to the same heading level as the first in the selection, which wasn't possible before (since `onChange` doesn't fire if you select the same option).
- `MenuSelectHeading`: Add "Styles" as default tooltip (as shown above). This can be overridden with `tooltipTitle` prop. Formerly no tooltip was shown by default, inconsistent with other controls.
- `MenuSelectFontSize` and  `MenuSelectFontFamily`: When content with multiple different font sizes or multiple different font families are selected, respectively, show the default …
=> Improve Select interfaces to handle selection containing multiple different values

.eslintrc.json, src/hooks/useDebouncedFunction.ts
This should make sure we are tree-shakable in all/most end-user bundlers.
This is a helpful reference on this front
https://itnext.io/lodash-es-vs-individual-lodash-utilities-size-comparison-676f14b07568
I considered lodash-es, but its usage seems rarer in many existing popular JS packages, so sticking with module-specific "lodash/foo" imports should ensure we are tree-shakable, while also using the version of lodash that many other packages will already have as a dependency (and instead avoid yet another dependency being installed in end users' projects). Also considered projects like radash, typedash, etc, but avoiding them for the same reason as lodash-es. We do only use a couple utils (debounce,t hrottle, omit) for what it's worth.
=> Ensure only specific modules of lodash are ever imported

package.json
For tree-shaking purposes with Webpack since we don't rely on any global side effects
(https://webpack.js.org/guides/tree-shaking/,
https://sgom.es/posts/2020-06-15-everything-you-never-wanted-to-know-about-side-effects/)
=> Mark package as being side-effect-free

src/index.ts
These props were added at some point recently but the type wasn't yet exported.
=> Export Props types for BubbleMenu components

src/controls/MenuSelect.tsx, src/controls/MenuSelectTextAlign.tsx
This ensures that (in light mode) if a Select controls component renders an icon for the current value (and for the MenuSelectTextAlign, for the options too), it matches the color of the non-selected MenuButton controls and the color of the select dropdown arrow.
Notice it was falling back to the default text color (dark grey) instead of using the lighter grey ("active") for the icons inside Selects:
| before | after |
|--------|--------|
| ![image](https://github.com/sjdemartini/mui-tiptap/assets/1647130/d73c6957-6ac7-4878-9ad2-3da63b1447b7) | ![image](https://github.com/sjdemartini/mui-tiptap/assets/1647130/abcb43ed-e945-479c-b3d8-b7b521db700c) |
=> Use matching icon colors in Select controls (in light mode)

src/index.ts, src/styles.ts
Technically a breaking change, but these weren't used internally in any published version and have never been documented officially, so shouldn't have been used in any consuming code.
=> Remove unused/undocumented style constants and function

src/MenuDivider.tsx, src/index.ts
Now users can use `sx={{ borderColor: 'red' }}` for instance, or pass in their own `className`, etc.
No change in UI.
=> Allow prop overrides and styling for MenuDivider

src/controls/MenuButton.tsx
Rather than hard-coding the name separately. For consistency with other mui-tiptap components.
=> Use component as makeStyles param for MenuButton

package.json
In order to separately export from two different modules, `"mui-tiptap"` and `"mui-tiptap/icons"`, typically our existing `"exports"` configuration in package.json would be sufficient. However, it turns out that this only supports importing the non-root module in a TS application if the consuming package that installs mui-tiptap uses `moduleResolution` of `Node16`, `NodeNext`, `bundler`, etc. but *not* `node` (the default, and the option suggested by TS in their official docs here
https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies).
As a (semi-hacky) workaround, we define `typesVersions` so that we can be compatible with `node`/`node10` resolution in consuming packages for our separate `"mui-tiptap/icons"` module.
Some resources related to …
=> Add typesVersions to package.json to support usage with `"node"` resolution

src/controls/MenuButtonHighlightColor.tsx
If highlighting is active but the Tiptap state has color is empty, we should fall back to showing the "active color" in button and color-picker as the defaultMarkColor. We were already doing this if the color was `null`, but this fixes it so it behaves that way if the `color` attribute is an empty string too.
=> Fall back to default mark color if highlight is active but has "" color

src/controls/MenuButtonTextColor.tsx
We'll now show no color in the indicator if there are multiple colors within the current selection. This is more in line with how we handle font family and font size, and how other rich text editors behave. 
Follow up to @ericdwang's comment here https://github.com/sjdemartini/mui-tiptap/pull/139#issuecomment-1693790578
Demo:
=> Improve "active text color" logic when multiple colors in selection

src/demo/SuggestionList.tsx, src/demo/mentionSuggestionOptions.ts
It's actually a list of suggestions (for use with the Mention extension), rather than being a list of "mentions". This deviates from Tiptap's example, but I feel is a clearer naming convention.
=> Rename `MentionList` -> `SuggestionList` in demo example for clarity

CONTRIBUTING.md, src/icons/FormatInkHighlighter.tsx
As seen here
https://github.com/sjdemartini/mui-tiptap/actions/runs/6148807694/job/16683337943?pr=149#step:12:24
Seems they removed/changed that route.
=> Update iconbuddy link to resolve 404

src/demo/Editor.tsx, src/utils/images.ts
This is more consistent with Tiptap's util parameter naming, and "insertPosition" was redundant given the function name. Technically a "breaking" API change, but was just released, wasn't documented explicitly, and is a straightforward update.
=> Rename `insertImages` position option for brevity

package.json
Fixes https://github.com/sjdemartini/mui-tiptap/issues/152 and https://github.com/sjdemartini/mui-tiptap/issues/151. This seems to be due to a bug in only-allow that specifically affects `npm`, where the `only-allow` goes into effect even when installing the package as a dependency: https://github.com/pnpm/only-allow/issues/13
=> Remove only-allow pre-install due to issue installing with npm

.eslintrc.json
Per
https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports.
Related to this issue/discussion https://github.com/sjdemartini/mui-tiptap/issues/154
=> Disallow imports of third-level MUI "private" paths

package.json
Run `pnpm visualize` kick of the bundle size analysis/visualization:
=> Add simple npm package script for bundle size visualizer

src/controls/ColorSwatchButton.tsx, src/controls/MenuButtonAddImage.tsx, src/controls/MenuButtonBlockquote.tsx, src/controls/MenuButtonBold.tsx, src/controls/MenuButtonBulletedList.tsx, src/controls/MenuButtonCode.tsx, src/controls/MenuButtonEditLink.tsx, src/controls/MenuButtonIndent.tsx, src/controls/MenuButtonItalic.tsx, src/controls/MenuButtonOrderedList.tsx, src/controls/MenuButtonRemoveFormatting.tsx, src/controls/MenuButtonStrikethrough.tsx, src/controls/MenuButtonSubscript.tsx, src/controls/MenuButtonSuperscript.tsx, src/controls/MenuButtonTaskList.tsx, src/controls/MenuButtonUnindent.tsx, src/controls/MenuSelectFontSize.tsx, src/controls/TableMenuControls.tsx, src/demo/Editor.tsx, src/extensions/HeadingWithAnchorComponent.tsx
Changed the import paths to ensure all mui/icons-material follow a direct import path.
Related is an issue which I just opened https://github.com/sjdemartini/mui-tiptap/issues/154  .
This should solve the issue. I verified that the affected controls still work as intended. 
Please let me know of any changes required. Thanks for your patience as this is my first open source PR. I did my best to follow the contribution guidelines and ran all checks.
=> fix: change remaining mui-icons to path imports

.eslintrc.json
To avoid regressions after fixing https://github.com/sjdemartini/mui-tiptap/issues/154.
=> Add eslint rule to enforce MUI icon default import paths

src/controls/MenuButtonUnindent.tsx
Resolves https://github.com/sjdemartini/mui-tiptap/issues/168
Seems this was due to a typo in
https://github.com/sjdemartini/mui-tiptap/pull/155, so this bug (showing the "indent" icon for the "unindent" button) affected v1.8.3.
=> Fix MenuButtonUnindent icon

src/ControlledBubbleMenu.tsx, src/FieldContainer.tsx, src/MenuBar.tsx, src/RichTextContent.tsx, src/RichTextField.tsx, src/extensions/HeadingWithAnchorComponent.tsx
Fixes https://github.com/sjdemartini/mui-tiptap/issues/178
In certain build setups, we can't use `function.name`, since the function will be mangled/minified, and so to ensure the MuiTiptap classes (like `MuiTiptap-RichTextField-content`) are static and consistent, we have to hard-code the component names as strings.
=> Prevent static class names from getting mangled in build

example/package.json, example/pnpm-lock.yaml, package.json, pnpm-lock.yaml
Resolves https://github.com/sjdemartini/mui-tiptap/security/dependabot/9 like https://github.com/sjdemartini/mui-tiptap/pull/190 did for the main pnpm-lock.
=> Bump Vite to 4.5.2 to resolve security warning

.vscode/settings.json
This changed was made automatically when opening VSCode.
=> Update VSCode settings for eslint fix per new syntax

src/controls/MenuButtonImageUpload.tsx
Fixed same image file upload issue for MenuButtonImageUpload.tsx.
For example, after uploading 1.jpg, uploading same file 1.jpg again did not trigger onChange trigger.
I added clear input value logic.
=> Fix the same file image upload issue

example/package.json, example/pnpm-lock.yaml, package.json, pnpm-lock.yaml
> Vite dev server option server.fs.deny did not deny requests for patterns with directories. An example of such a pattern is /foo/**/*.
Fixed in 4.5.3.
Doesn't affect us, and only a dev dep, but bumping to remove the alerts.
=> Bump Vite to newer patch version to silence Dependabot alerts

src/controls/MenuSelectHeading.tsx
Fix issue #197 
I have modified the code by moving the variable` level `outside the scope of the if statement and renamed it to `currentLevel `for greater specificity. Additionally, I have included `currentLevel `in the conditions for `canSetHeading`.
Please excuse any oversights as I am new to contributing and still familiarizing myself with the process.
=> Fix issue where other heading levels are disabled when Heading 1 is selected

src/extensions/ResizableImage.ts, src/extensions/ResizableImageComponent.tsx
This will allow users of ResizableImage to inject their own custom child component. My use case is to add a custom button overlaid over the image.
=> add option to add a child component to images

pnpm-lock.yaml
Should fix dependency audit in CI (e.g. [here](https://github.com/sjdemartini/mui-tiptap/actions/runs/9609312278/job/26503587717#step:5:42) and [here](https://github.com/sjdemartini/mui-tiptap/actions/runs/9598457872/job/26469796810?pr=231))
=> Fix security warnings for transitive dependencies ws and braces

src/extensions/ResizableImageComponent.tsx, src/extensions/ResizableImageResizer.tsx, src/styles.ts
Before this change, even if `inline: true` was set for `Image` or `ResizableImage`, the image would still appear as a block element (thanks to mui-tiptap's styles and the NodeView element type of `div`) and so would not be truly "inline", largely defeating the purpose of `inline: true`. Corrected here.
Here are screenshots with `ResizableImage.configure({ inline: true })`. Before, it would show up as non-inline due to the styles/elements being used.
| before | after |
|--------|--------|
| <img width="848" alt="Screenshot 2024-06-23 at 10 47 49 PM" src="https://github.com/sjdemartini/mui-tiptap/assets/1647130/1df56260-3f5e-4a4e-b0cb-f05f1ec1a02e"> | <img width="1053" alt="Screenshot 2024-06-23 at 10 47 36 PM" src="https://github.com/sjdemartini/mui-tiptap/assets/1647130/38c9fa0e-b012-48fc- …
=> Support inline and non-inline configuration styling for ResizableImage/Image

src/controls/MenuSelectHeading.tsx
=> Fix bug not being able to disable H1

src/RichTextEditor.tsx
Fixes https://github.com/sjdemartini/mui-tiptap/issues/249 while still remaining backward compatible, allowing mui-tiptap users to use the new React-specific editor options if they're on Tiptap 2.5+
(https://tiptap.dev/blog/release-notes/say-hello-to-tiptap-2-5-our-most-performant-editor-yet), like:
```ts
<RichTextEditor extensions={[]} immediatelyRender />
```
=> Update RichTextEditor types to support Tiptap 2.5+ options

src/RichTextEditor.tsx, src/RichTextReadOnly.tsx
We should support the new Tiptap 2.5+ props for `RichTextReadOnly` like 9e98e24 did for `RichTextEditor`, as pointed out in https://github.com/sjdemartini/mui-tiptap/issues/249#issuecomment-2249020284. e.g.
```tsx
<RichTextReadOnly
content={content}
extensions={extensions}
immediatelyRender
/>
```
=> Update RichTextReadOnly types to support Tiptap 2.5+ options

.github/workflows/build-test.yml, example/pnpm-lock.yaml, package.json, tsconfig.build.json
_Third_ attempt to resolve https://github.com/sjdemartini/mui-tiptap/issues/256 😅   (should supersede https://github.com/sjdemartini/mui-tiptap/pull/258 and https://github.com/sjdemartini/mui-tiptap/pull/257, see the former for more details/discussion)
Should resolve https://github.com/sjdemartini/mui-tiptap/issues/256
Both `@mui/icons-material` (https://github.com/mui/material-ui/issues/35233) and `lodash` (https://github.com/lodash/lodash/issues/5107) have problems being imported in a consuming package when using ESM. The workarounds attempted in https://github.com/sjdemartini/mui-tiptap/pull/258 almost seemed to work (didn't break a downstream bundled package using Vite), but still caused problems for the original example node application …
=> Force node to use CJS to get around dependency import errors, and validate package types in CI

src/controls/MenuSelectHeading.tsx
The shortcuts can be kind of too much for some users. There is no way to remove them from user space not even with CSS so it would make sense to add a prop that allows that customization
=> Allow hiding shortcuts for MenuSelectHeading

CONTRIBUTING.md
Avoid mistakenly pushing other tags, like what happened as mentioned here https://github.com/sjdemartini/mui-tiptap/pull/267#issuecomment-2344978118
=> Suggest pushing specific tag instead of all tags for releasing

.github/workflows/build-test.yml, package.json
When `"type": "commonjs"` is specified in our package.json, it apparently causes the following problem in NextJS:
```
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
> export { default as ControlledBubbleMenu, } from "./ControlledBubbleMenu";
| export { default as LinkBubbleMenu, } from "./LinkBubbleMenu";
| export { default as MenuBar } from "./MenuBar";
```
This is odd, since we indeed *are* using "commonjs" type, as that's the default (https://nodejs.org/api/packages.html#type), but it seems that fortunately merely omitting this resolves import errors in NextJS, and still supports NodeJS, based on my testing.
Should resolve https://github.com/sjdemartini/mui-tiptap/issues/264, removing one of the changes from …
=> Remove type: "commonjs" to fix importing in NextJS

src/LinkBubbleMenu/EditLinkMenuContent.tsx, src/LinkBubbleMenu/index.tsx, src/utils/index.ts, src/utils/links.ts
Resolves: https://github.com/sjdemartini/mui-tiptap/issues/182 and https://github.com/sjdemartini/mui-tiptap/issues/275
Changes:
- The default behavior of the LinkBubbleMenu editing is to do the following to the user-entered URL when they finish typing:
- trim leading/trailing whitespace (unchanged)
- ensure the value has a protocol (http://) if it doesn't already and isn't a relative (starting with "/") or anchor (starting with "#") URL **(_change in behavior_)**
- Change: We now accept relative URLs starting with "/" and anchor links starting with "#"  (resolves #275)
- Change: We now also accept `sms:` as a valid protocol, like we did for `mailto:` and `tel:` before
- URL-encode the result (unchanged)
- `LinkBubbleMenu` now has a `formatHref` prop which can be used to override the …
=> Allow relative and anchor links in link edit menu, and allow users to override link-formatting behavior

src/ControlledBubbleMenu.tsx, src/controls/ColorPickerPopper.tsx, src/demo/App.tsx, src/demo/Editor.tsx, src/styles.ts
Bringing back the functionality of https://github.com/sjdemartini/mui-tiptap/pull/225.
Overwhelming consensus and convention is to have poppers use the `tooltip` zIndex to always appear above modals, which affects 
Two "breaking" changes as a result:
1. The z-index for the bubble menus (`ControlledBubbleMenu`, `LinkBubbleMenu`, `TableBubbleMenu`) and poppers (`ColorPickerPopper` via `MenuButtonHighlightColor` and `MenuButtonTextColor`) will now be `theme.zIndex.tooltip`
2. The `Z_INDEXES` object (exported from `mui-tiptap`) removes the `BUBBLE_MENU` value. You should instead reference `theme.zIndex.tooltip` to get the z-index used for the bubble menus, as mui-tiptap does not define the value internally.
Relates to and resolves these issues/PRs:
- …
=> Use MUI theme tooltip zIndex for popper menus to appear above modals

package.json, pnpm-lock.yaml
Removes an underlying deprecated dependency (`rimraf@3.0.2`).
=> Upgrade cspell to latest (v6 -> v8)

src/ControlledBubbleMenu.tsx
This should make it easier to override styles like `zIndex` and more for the `ControlledBubbleMenu`, as well as the `LinkBubbleMenu` and `TableBubbleMenu` that utilize it under the hood. e.g.:
```tsx
<LinkBubbleMenu sx={{ "&&": { zIndex: 100 } }} />
```
Overriding the styles has been a common request, such as in https://github.com/sjdemartini/mui-tiptap/pull/291#issuecomment-2480911008, and in examples here https://github.com/sjdemartini/mui-tiptap/issues/206 (where folks were doing something similar specifically for `MenuButtonTextColor`'s `PopperProps`'s `sx` prop).
=> Expose `sx` prop for `ControlledBubbleMenu` styles

src/controls/MenuSelect.tsx
This ensures menu items aren't blocked, etc., and the tooltip need not continue to be displayed if you've already clicked the select, like:
Resolves https://github.com/sjdemartini/mui-tiptap/issues/308
=> Close MenuSelect tooltip when opening dropdown options

src/controls/MenuButtonStrikethrough.tsx
Hello, just noticed this small issue. Thought Id push a quick fix.
Thank you for this. You're a hero for building it.
=> Strike through menu button shortcut should use "S" instead of "X"

src/controls/ColorPicker.tsx
In relation to #320, adds utility classes to `ColorPicker` so users can override/extend the default styles of the gradient picker, text input, and swatch container. This provides extensive customisability to any components making use of the ColorPicker. It introduces a `classes` prop to control the styling by merging custom class names with the default generated utility classes.
- Added a `colorPickerUtilityClasses` constant generated by the `getUtilityClasses` helper.
- Exposed `gradientPicker`, `colorTextInput`, and `swatchContainer` for ColorPicker.
- Introduced a `classes` prop on `ColorPickerProps`.
- Applied utility classes to the `<HexColorPicker>`/`<HexAlphaColorPicker>`, `<TextField>`, and swatch container `<div>`.
Apply the desired CSS class to the `ColorPickerProps`:
```js …
```
=> Add utility classes to ColorPicker component

.github/dependabot.yml
This are relatively frequent, we intentionally support old versions, etc., so don't want the dependabot spam of bumping all of these continuously for the local dev deps.
=> Ignore tiptap packages for dependabot updates

src/styles.ts
Fixes https://github.com/sjdemartini/mui-tiptap/issues/339
As mentioned in the code, consumers should likely use a nested `ThemeProvider` around mui-tiptap components (https://mui.com/material-ui/customization/theming/#nesting-the-theme) to define the typography styles they want to use if their main theme doesn't include them, based on MUI's default typography variants. That way consumers can bake their preferred editor typography styles into mui-tiptap's default CSS.
Here's how it looks with all MUI typography variants removed in the theme, which is still decent thanks to browser defaults for the heading elements:
=> Don't crash if MUI theme typography variants were removed

.github/dependabot.yml
Codifying in the config what was done here
https://github.com/sjdemartini/mui-tiptap/pull/367#issuecomment-3024440495
=> Ignore major version bumps of type-fest

src/extensions/ResizableImageResizer.tsx
Without this fix, clicking and trying to drag the resizer would instead end up dragging the whole image, for versions of Tiptap 2.11 onward.
=> Fix bug with resizable image resizer on Tiptap 2.11+

.github/workflows/build-test.yml
Potential fix for [https://github.com/sjdemartini/mui-tiptap/security/code-scanning/1](https://github.com/sjdemartini/mui-tiptap/security/code-scanning/1)
To fix the error, we will add a `permissions` block at the root level of the workflow. This block will specify the minimal permissions needed for the workflow to operate. Based on the provided workflow, the `contents: read` permission should suffice because there is no indication of actions requiring write access (e.g., modifying pull requests or repository contents).
- The `permissions` block will be added at the root level (after the `name` field) to apply to all jobs in the workflow.
- The block will specify `contents: read` to explicitly limit the `GITHUB_TOKEN`'s permissions to read-only access to repository contents.
--- …
=> Potential fix for code scanning alert no. 1: Workflow does not contain permissions

example/pnpm-lock.yaml, pnpm-lock.yaml
Did this in the main package by adding this, running `pnpm i`, then removing it:
```
"pnpm": {
"overrides": {
"linkifyjs@^4.1.0": "4.3.2"
}
},
```
since pnpm doesn't support updating transitive deps via any direct way.
=> Bump linkifyjs dev dep in main and example packages to resolve security warning

src/styles.ts
Per the new "caret" (instead of "cursor") extension https://tiptap.dev/docs/editor/extensions/functionality/collaboration-caret and the class names it uses.
https://tiptap.dev/docs/guides/upgrade-tiptap-v2#package-changes
| before, when using Tiptap v3 | after (Tiptap v2 or v3) |
|--------|--------|
| <img width="590" height="212" alt="Screenshot 2025-09-02 134106" src="https://github.com/user-attachments/assets/bf90867d-f4dd-4927-a5c7-bd57b522f517" /> | <img width="558" height="214" alt="Screenshot 2025-09-02 134053" src="https://github.com/user-attachments/assets/9347ca59-d850-476d-856a-88b0ee1c72f6" /> |
=> Update styles for collaboration carets to support Tiptap v3

.github/workflows/build-test.yml, example/tsconfig.json
As an extra guarantee of correctness, to make it easier to confidently bump TS in the dev dependencies of the package without worrying about breaking things for users on older TS.
=> Validate minimum TS version in CI

src/extensions/ResizableImageComponent.tsx
Fixes https://github.com/sjdemartini/mui-tiptap/issues/453
Empty string `title` does have a specific purpose
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/title#title_attribute_inheritance, so we may as well support it too.
=> Render empty string `alt`/`title` attrs if explicitly set for `ResizableImage`

src/extensions/HeadingWithAnchor.ts
`editor.options.element` wasn't the most precise way of checking this, though did the trick. As of Tiptap 3.6 though, that option is more dynamic (https://github.com/ueberdosis/tiptap/releases/tag/v3.6.0), so we must use the view. Should've really been `editor.view.dom` all along.
Revealed in
https://github.com/sjdemartini/mui-tiptap/actions/runs/18062457728/job/51400637779
Tested autoscroll in the demo with this quick diff:
```diff
diff --git a/src/demo/Editor.tsx b/src/demo/Editor.tsx
index fe820aa..cd0e8c1 100644
--- a/src/demo/Editor.tsx
+++ b/src/demo/Editor.tsx
@@ -6,7 +6,7 @@ import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import type { EditorOptions } from "@tiptap/core";
-import { useCallback, …
```
=> Make HeadingWithAnchor autoscroll work consistently on Tiptap 3.6+

.github/workflows/build-test.yml
So we are less likely to discover things like https://github.com/sjdemartini/mui-tiptap/actions/runs/18062457728/job/51400637779  (https://github.com/sjdemartini/mui-tiptap/pull/463) via unrelated changes.
=> Run CI on weekly schedule to proactively catch breaking changes

src/controls/MenuButton.tsx, src/controls/MenuSelectTextAlign.tsx
For all `MenuButton`s and for the options within `MenuSelectTextAlign`. Fixes https://github.com/sjdemartini/mui-tiptap/issues/458.
=> Add aria-label for accessibility of (icon-only) menu buttons & options
