package.json, pnpm-lock.yaml, src/EditLinkMenuContent.tsx, src/ViewLinkMenuContent.tsx, src/hooks/index.ts, src/hooks/useKeyDown.ts
Yet more trimming/simplifying!
=> Replace react-use useKey with custom useKeyDown hook, and remove react-use

example/pnpm-lock.yaml, package.json, pnpm-lock.yaml
- [Remove material-ui-popup-state](https://github.com/sjdemartini/mui-tiptap/commit/7d18a56d31c3a80859ae16006b931135a075cabf) (unused)
- [Move some prosemirror packages to devDependencies](https://github.com/sjdemartini/mui-tiptap/commit/c6fda5512cb2edadb0ed5b3ff28730e57ded638b) — These are already listed as peers so need not be listed in dev dependencies.
=> Remove more direct dependencies

src/RichTextField.tsx, src/TableBubbleMenu.tsx, src/controls/MenuControlsContainer.tsx, src/index.ts
This also exports the DebounceRender component for direct or more customized uses that users may have.
=> Allow users to debounce menu controls, and control debounce options

src/controls/MenuButtonRedo.tsx, src/controls/MenuButtonUndo.tsx, src/demo/EditorMenuControls.tsx
As suggested in https://github.com/sjdemartini/mui-tiptap/issues/52
=> Add Undo and Redo menu buttons

package.json, pnpm-lock.yaml, src/controls/MenuButtonHorizontalRule.tsx, src/demo/EditorMenuControls.tsx, src/demo/useExtensions.ts, src/styles.ts
Also tweak local dev extensions list to use all heading levels
=> Add button and specific styles for Horizontal Rule

src/demo/useExtensions.ts, src/extensions/ResizableImageComponent.tsx
=> Add support for text-align with ResizableImage

src/demo/Editor.tsx
So clicking on the anchor links jumps the scroll position to a useful spot.
=> Update scroll margin for headings in demo

README.md
I'm removing the mention of MUI to avoid the possible confusion between the organization (MUI) and the open source project (Material UI) that implements Material Design.
Great to see this project. If it reach >100 stars, don't hesitate to propose to link it in https://mui.com/material-ui/discover-more/related-projects/#components
=> Only covering Material UI

.vscode/extensions.json, README.md, example/package.json, example/pnpm-lock.yaml, example/src/App.tsx, example/src/PageContentWithEditor.tsx, example/src/PageContentWithEditorSimple.tsx, src/RichTextReadOnly.tsx
Also include markdown all-in-one extension rec for README Table of Contents
=> Make minor tweaks to improve README and examples

README.md, src/controls/MenuSelectFontSize.tsx, src/controls/MenuSelectTextAlign.tsx, src/extensions/ResizableImageResizer.tsx
Resolves https://github.com/sjdemartini/mui-tiptap/issues/59
=> Document options for localization and content overrides

.eslintrc.json, .github/workflows/build-test.yml, example/pnpm-lock.yaml, tsconfig.json
Catch problems in `/demo` (and potentially other local dev stuff in the future) as well.
=> Run type check as part of CI (separate from build)

.github/PULL_REQUEST_TEMPLATE.md
=> Remove GitHub PR template

src/controls/MenuButton.tsx, src/controls/MenuSelect.tsx
Follow-on to https://github.com/sjdemartini/mui-tiptap/pull/130
Before:
After:
=> Show MenuSelect rendered icons with disabled color when disabled

CONTRIBUTING.md, src/controls/MenuButtonHighlightColor.tsx, src/controls/MenuButtonHighlightToggle.tsx, src/icons/FormatInkHighlighter.tsx, src/icons/index.ts
| Before | After |
|--------|--------|
| ![Screenshot 2023-08-25 at 9 08 10 AM](https://github.com/sjdemartini/mui-tiptap/assets/1647130/1e2125c5-acfe-4757-941f-8e473fa362a3)  | ![Screenshot 2023-08-25 at 9 08 01 AM](https://github.com/sjdemartini/mui-tiptap/assets/1647130/21a05792-ac07-41f4-8334-344401686711) |
=> Add FormatInkHighlighter icon and use in Highlight buttons, and add contributing notes on adding icons to mui-tiptap

.cspell.json
As in this job https://github.com/sjdemartini/mui-tiptap/actions/runs/5980772059/job/16227559196
=> Add more cspell words to fix its failure

src/controls/ColorPicker.tsx, src/controls/ColorSwatchButton.tsx
=> Show checkmark over currently active swatch preset

.github/workflows/build-test.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
This should allow running CI for https://github.com/sjdemartini/mui-tiptap/pull/155 (once it's rebased).
=> Run CI for pull requests (not just pushes to this repo directly)

example/package.json, example/pnpm-lock.yaml, package.json, pnpm-lock.yaml
Should resolve
https://github.com/sjdemartini/mui-tiptap/security/dependabot/7 and https://github.com/sjdemartini/mui-tiptap/security/dependabot/8
=> Update Vite to latest 4.* version

.github/ISSUE_TEMPLATE/bug_report.md
Since it's common to get questions/"issues" pertaining to this and is important to help diagnose as well.
e.g. https://github.com/sjdemartini/mui-tiptap/issues/187, https://github.com/sjdemartini/mui-tiptap/issues/174, https://github.com/sjdemartini/mui-tiptap/issues/136#issuecomment-1986356215
=> Add info about extensions to bug report template

src/RichTextEditor.tsx
This is related to https://github.com/sjdemartini/mui-tiptap/issues/260
=> Update RichTextEditor to update ref handle only when editor changes

eslint.config.mjs
=> Use more targeted eslint disables in eslint.config.mjs, and disable some redundant eslint-plugin-import rules

package.json
=> Bump pnpm version to latest (9.12.1 -> 9.13.2)

package.json
* Update `package.json` to include React 19 in `peerDependencies` for both `react` and `react-dom`.
=> feat: update `peerDependencies` to support React 19

.github/dependabot.yml, package.json, pnpm-lock.yaml, src/RichTextEditor.tsx, src/RichTextReadOnly.tsx, src/controls/MenuButton.tsx, src/controls/MenuButtonAddImage.tsx, src/controls/MenuButtonColorPicker.tsx, src/controls/MenuButtonImageUpload.tsx, src/controls/MenuControlsContainer.tsx, src/controls/MenuSelectFontFamily.tsx, src/controls/MenuSelectFontSize.tsx, src/controls/MenuSelectHeading.tsx, src/controls/MenuSelectTextAlign.tsx
Making install size smaller and minimizing use of external packages where possible
=> Remove type-fest dependency in favor of builtin types

src/ControlledBubbleMenu.tsx
Obsolete comment after https://github.com/sjdemartini/mui-tiptap/pull/291
=> Remove stale comment since zIndex no longer problematic in dialog
